version: 1.0
prototypes:
  - type: current
    # TODO: This is a hack around the following in the SDK:
    # prototype and instance config mismatch (model): SNMP != PXGMS UPS + EATON 93PM
    # For SNMP, the sdk should not check the model. SNMP should allow for
    # determining the model by interrogating the device.
    # This hack is in every file in this directory.
    model: PXGMS UPS + EATON 93PM
    manufacturer: SNMP
    protocol: SNMP
    output:
      - type: current
        data_type: float
        unit:
          name: amps
          symbol: A
        precision: 3
