version: 1.0
prototypes:
  - type: frequency
    model: SNMP # TODO: Check to see that this is overridden.
    manufacturer: SNMP # TODO: Check to see that this is overridden.
    protocol: SNMP
    output:
      - type: frequency
        data_type: float
        unit:
          name: hertz
          symbol: Hz
        precision: 3
