version: 1.0
prototypes:
  - type: voltage
    # model: SNMP # TODO: Check to see that this is overridden.
    model: PXGMS UPS + EATON 93PM # TODO: This is a hack around: prototype and instance config mismatch (model): SNMP != PXGMS UPS + EATON 93PM
    manufacturer: SNMP # TODO: Check to see that this is overridden.
    protocol: SNMP
    output:
      - type: voltage
        data_type: float
        unit:
          name: volts
          symbol: V
        precision: 3
