version: 1.0
prototypes:
  - type: voltage
    model: PXGMS UPS + EATON 93PM
    manufacturer: SNMP
    protocol: SNMP
    output:
      - type: voltage
        data_type: float
        unit:
          name: volts
          symbol: V
        precision: 3
