version: 1.0
name: snmp
debug: true
network:
  type: unix
  address: snmp.sock
settings:
  mode: serial
  read:
    interval: 3s
    buffer: 1024
  write:
    interval: 1s
    buffer: 1024
  transaction:
    ttl: 30s
