version: 1.0
name: snmp
debug: true
network:
  type: unix
  address: snmp.sock
settings:
  mode: serial
  read:
    interval: 3s
    buffer: 1024
  write:
    interval: 1s
    buffer: 1024
  transaction:
    ttl: 30s
auto_enumerate:
  - model: PXGMS_UPS
    version: v3
    endpoint: 127.0.0.1
    port: 1024
    userName: simulator
    authenticationProtocol: SHA
    authenticationPassphrase: auctoritas
    privacyProtocol: AES
    privacyPassphrase: privatus
    contextName: public
