# Device configuration for the Eaton® Power Xpert® Gateway Minislot PXGMS UPS Card.
# TODO: Parameter values will likely change.
version: 1.0
locations:
  r1vec:
    rack: rack-1
    board: snmp1
devices:
  - type: snmp
    model: PXGMS_UPS
    instances:
      - version: v3
        endpoint: 127.0.0.1
        port: 1024
        userName: simulator
        authenticationProtocol: SHA
        authenticationPassphrase: auctoritas
        privacyProtocol: AES
        privacyPassphrase: privatus
        contextName: public
